Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_url = "https://app.vagrantup.com/bento/boxes/ubuntu-22.04"

  config.vm.define "hahadiouS" do |server|
    server.vm.hostname = "hahadiouS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "vmware_desktop" do |v|
      v.memory = 1024
      v.cpus = 1
      v.gui = false
      v.vmx["displayName"] = "hahadiouS"
    end

    server.vm.provision "shell", path: "scripts/server_provision.sh"
  end
end 