global:
  hosts:
    domain: localhost
    https: false
  ingress:
    configureCertmanager: false
    class: traefik
    enabled: false
  minio:
    enabled: false
  appConfig:
    artifacts:
      enabled: false
    lfs:
      enabled: false
    uploads:
      enabled: false
    packages:
      enabled: false
    object_store:
      enabled: false
  gitaly:
    persistence:
      enabled: false
  psql:
    host: postgresql
    password:
      secret: gitlab-postgres
      key: postgresql-password
  redis:
    auth:
      enabled: false
  shell:
    port: 32022
  workhorse:
    port: 8181
  kas:
    enabled: false
  pages:
    enabled: false
  registry:
    enabled: false
  praefect:
    enabled: false
  spamcheck:
    enabled: false
  webservice:
    extraEnv:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 32022
gitlab:
  gitaly:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
      limits:
        memory: 400Mi
        cpu: 200m
    replicas: 1
    startupProbe:
      enabled: false
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
  gitlab-shell:
    service:
      type: ClusterIP
      port: 32022
  webservice:
    service:
      type: ClusterIP
      port: 8181
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
      limits:
        memory: 400Mi
        cpu: 200m
    replicas: 1
    startupProbe:
      enabled: false
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    extraEnv:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 32022
    init:
      resources:
        requests:
          memory: 100Mi
          cpu: 50m
        limits:
          memory: 200Mi
          cpu: 100m
  sidekiq:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 200Mi
        cpu: 100m
    replicas: 1
    startupProbe:
      enabled: false
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    init:
      resources:
        requests:
          memory: 100Mi
          cpu: 50m
        limits:
          memory: 200Mi
          cpu: 100m
  toolbox:
    enabled: false
postgresql:
  persistence:
    enabled: false
  resources:
    requests:
      memory: 100Mi
      cpu: 50m
    limits:
      memory: 200Mi
      cpu: 100m
  primary:
    podAnnotations:
      "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    startupProbe:
      enabled: false
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
redis:
  master:
    persistence:
      enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 50m
      limits:
        memory: 200Mi
        cpu: 100m
    podAnnotations:
      "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    startupProbe:
      enabled: false
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
nginx-ingress:
  enabled: false
certmanager:
  install: false
prometheus:
  install: false
gitlab-runner:
  install: false
