apiVersion: v1
kind: Secret
metadata:
  name: gitlab-minio-secret
  namespace: gitlab
type: Opaque
stringData:
  connection: |
    provider: AWS
    region: us-east-1
    aws_access_key_id: minio
    aws_secret_access_key: minio123
    endpoint: http://minio:9000
    path_style: true
